* Create recycle package
** develop core functionality in R package
Purpose: develop proto type code provided in R functions into a package called recycle.

*** Main functionality
The objective of the recycle package is to check function arguments for whether a rerun of the function is necessary, or stored results can be reused. The interface function should be 

#+begin_src R
recycle(myfun,args,env,path.res,funs.unwrap)
#+end_src

`funs.unwrap` must be replaced or accompanied by an interface that also allows for provided file paths to be read, or as provided in custom functions. Not sure `funs.unwrap` is necesary, or an arg could specify that functions must be handled the way funs.unwrap specifies for now.

Also, add an argument to recycle() to specify an rds file to read/store digests to compare against. Then recycle should not use the path.res argument in `myfun3()`.

Functions  needrun and needrun2 are both defined. I _think_ needRun2 is a better/simpler implementation.

*** Handling the environment or `env`
I am not sure the best way to handle this. Maybe, to begin with, the most robust way is to pass the environment, manually to recycle(). The solution must work from an interactive environment, as well as within packages, like pkg2::fun2(recycle=TRUE) should allow fun2 to use recycle() internally. 


** additional code
#+begin_src R

  ########## example
  ## this example is a function that attempts to "recycle". The interface recycle() should be simpler.
  
if(F){
  ##### myfun3 is a function that internally makes use of needRun2. It

  ## the big q is how we handle functions from within packages

  myfun3 <- function(x,path.res){
    ## not sure this is quite enough. I just put in getArgs() because I think we can use that somehow.
    obj <- getArgs()
    ### fnExtension doesn't matter as long as we use readRDS to read results. 
    path.digs <- fnExtension(fnAppend(path.res,"digests"),".rds")

    ### env should just be the myfun3 environment. How do I get that?
    must.run <- needRun2(obj,env=,path.digs=path.digs)
    if(must.run){
      res <- x+3
      ## if new digests were provided by needRun2, use those. Otherwise recalc
      if(!is.null(must.run$digest)){
        digs.new <- must.run$digest
      } else {
        digs.new <- digestElements(obj,env=,funs=funs.unwrap)
      }
      saveRDS(res,path.res)
      saveRDS(digs.new,path.digs)

      return(res)
    } else {
      readRDS(path.res)
    }

    res
  }

  ##### would be even better if we could do
  ## res <- recycle(myfun,args,env,path.res,funs.unwrap)

  
}

#+end_src

** Querries
Ask:
Are there solutions available already that can do this?

I need funs.unwrap because my argument values are often functions, and they must be compared by code without environment (which would break comparison). Can some of the other packages do this? Can they generally apply a function to some arguments (e.g. read file contents instead of path)?

can I include named columns in hash to be treated differently? Like if(x%in%c("myfile","myfile2") then read before digest?

If so, my need is maybe just a function to generate that repalacement for hash_fun_by_code that distinguishes. 

edit: Create DESCRIPTION and other R package necessities

agent:
- create tests with the recycle() function as explained
- develop R functions in recycle package, restructured and renamed appropriately. Store the R functions as separate new files in R/.
- Run tests of recycle, and iterate functions and test to success. 

I want one common interface for "unwrapping" arguments. args.unwrap=list(arg1="function",arg2=fread) )
Notice, "function" is a keyword to do the function unwrapping.

Also, "function" should be default if the value of the argument is a function.


some function, funwrite(), to be run within recycle() saves results already. recycle() must be able to 1) skip saving the results, ana 2) read the results from the specified output path. The output data could be saved in any format, so the user must have the option to specify a custom function to use for reading results.


digest must include md5 of results file. If results file changed since last run, also rerun.

include a "quiet" argument. If FALSE (default), message whether new run is being done and because of what digest changes. If new run not done, message what file is being read.

there is something wrong with the md5 check. It keeps rerunning the code. I can see that the md5 sum stored in the digests file doesn't match the md5sum() of file.res. Digests is supposed to keep the md5 of the last result, so recycle know if the digests of the arguments match the result file stored.


run check() and fix any issues. Never edit man .rd files, only edit rogy


fix check() note: 
 recycle: no visible binding for global variable ‘name’
  Undefined global functions or variables:


revise readme and vignette with respect to recent improvements. I wrote an example with NMsim and recycle in devel/NMsim_recycle.R - please use the syntax I am using. If this is not covered in vignette, please do.

I want the NMsim example in the vignette


For a function, pkg::fun, in package pkg that takes arguments a, b, c, ..., I want to add an argument called recycle. If recycle=TRUE, I want to use the recycle package internally. How can I pass on all the arguments that pkg::fun was called with and pass them to recycle within fun?
