##' Check if function needs to be re-run based on argument changes
##'
##' Compares current arguments against stored digests to determine if
##' a function needs to be re-executed.
##'
##' @param args Named list of arguments. Also see `digests`.
##' @param path.results Path to results file
##' @param path.digest Path to digest file
##' @param funs.unwrap Named list of functions to apply before digesting
##' @param digests if provided, these digests (as generated by `digest_list()`) will be used instead of recalculating from `args`.
##' @param force Logical, if TRUE always return that run is needed
##' @param quiet Logical, if FALSE prints messages about what changed
##' @return List with elements: run (logical), digest.new (data.table), digest.all (data.table or NULL)
##' @import data.table
##' @importFrom tools md5sum
##' @keywords internal

check_need_run <- function(args, path.results=NULL, path.digests, args.unwrap, digests, digests.old, force = FALSE, quiet = FALSE) {

  #### Section start: Dummy variables, only not to get NOTE's in package checks ####
  res.new <- NULL
  name <- NULL
  #### Section end: Dummy variables, only not to get NOTE's in package checks ####

  
  if(missing(digests)){
    # Calculate new digests
    digests.new <- digest_list(list=args, args.unwrap=args.unwrap,path.results=path.results)
  } else {
    digests.new <- digests
  }

  if(missing(digests.old)) digests.old <- NULL

  if(is.null(digests.old)){
    # Load old digests
    digests.old <- readRDS(path.digests)
  }
  
  ### this should be done a bit differently.
  ## goal: check old md5 against the md5 of the results on file.

  ## digest_list() needs to take an extra argument, path.results Include a column "type" that denotes "arg" or "res".

  # If results file doesn't exist, must run
  if (!file.exists(path.results)) {
    if (!quiet) {
      message(sprintf("Running function: results file does not exist (%s)", path.results))
    }
    return(list(run = TRUE, digests.new = digests.new, digests.all = NULL))
  }
  
  # Add MD5 of results file to digests (for comparison with old)
  res_file_md5 <- tools::md5sum(path.results)
  digests.new <- rbind(digests.new,
                      data.table(name="results",type="results",
                                 res=as.character(tools::md5sum(path.results))
                                 ))

  
  # If force=TRUE, always run
  if (force) {
    if (!quiet) {
      message("Running function (force = TRUE)")
    }
    return(list(run = TRUE, digests.new = digests.new, digests.all = NULL))
  }
  
  
  # If digest file doesn't exist, must run
  ## if (!file.exists(path.digest)) {
  if (is.null(digests)) {
    if (!quiet) {
      message(sprintf("Running function: Reference digests unavailable."))
    }
    return(list(run = TRUE, digests.new = digests.new, digests.all = NULL))
  }
  
  
  
  
  
  # Compare digests
  digests.all <- merge(digests.new, digests.old, by = "name", 
                      suffixes = c(".new", ".old"), all = TRUE)
  
  run <- FALSE
  
  # Check if any digests differ
  if (any(is.na(digests.all$res.new)) || 
        any(is.na(digests.all$res.old)) ||
        !all(digests.all$res.new == digests.all$res.old)) {
    
    if (!quiet) {
      # Identify what changed
      changed <- digests.all[is.na(res.new) | is.na(res.old) | res.new != res.old]
      
      if (nrow(changed) > 0) {
        change_msgs <- character(nrow(changed))
        for (i in seq_len(nrow(changed))) {
          arg_name <- changed$name[i]
          if (is.na(changed$res.old[i])) {
            change_msgs[i] <- sprintf("  - '%s': new argument", arg_name)
          } else if (is.na(changed$res.new[i])) {
            change_msgs[i] <- sprintf("  - '%s': argument removed", arg_name)
          } else if (arg_name == ".results_file_md5") {
            change_msgs[i] <- "  - Results file was modified externally"
          } else {
            change_msgs[i] <- sprintf("  - '%s': value changed", arg_name)
          }
        }
        message("Running function due to changes:")
        message(paste(change_msgs, collapse = "\n"))
      }
    }
    
    run <- TRUE
  }
  
  # No changes detected
  return(list(run = run, digest.new = digest.new, digest.all = digest.all))
}
